//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// home

export const HOME_GLOBAL = 'HOME_GLOBAL';
export const PUT_HOME_GLOBAL = 'PUT_HOME_GLOBAL';
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const GET_COUNTRY_DETAILS = 'GET_COUNTRY_DETAILS';
export const COUNTRY_DATA = 'REFRESH';
export const SET_COUNTRY_DETAILS = 'SET_COUNTRY_DETAILS';
export const GET_COUNTRY_NEWS = 'GET_COUNTRY_NEWS';
export const SET_COUNTRY_NEWS = 'SET_COUNTRY_NEWS';
export const GET_COUNTRY_TIMELINE = 'GET_COUNTRY_TIMELINE';
export const SET_COUNTRY_TIMELINE = 'SET_COUNTRY_TIMELINE';

//setttings
export const NOTIFICATION_STATE = 'NOTIFICATION_STATE';
